// Generated by gencpp from file neuromechanics_control/AnalogCompact.msg
// DO NOT EDIT!


#ifndef NEUROMECHANICS_CONTROL_MESSAGE_ANALOGCOMPACT_H
#define NEUROMECHANICS_CONTROL_MESSAGE_ANALOGCOMPACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neuromechanics_control
{
template <class ContainerAllocator>
struct AnalogCompact_
{
  typedef AnalogCompact_<ContainerAllocator> Type;

  AnalogCompact_()
    : header()
    , data()
    , names()  {
    }
  AnalogCompact_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)
    , names(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> const> ConstPtr;

}; // struct AnalogCompact_

typedef ::neuromechanics_control::AnalogCompact_<std::allocator<void> > AnalogCompact;

typedef boost::shared_ptr< ::neuromechanics_control::AnalogCompact > AnalogCompactPtr;
typedef boost::shared_ptr< ::neuromechanics_control::AnalogCompact const> AnalogCompactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neuromechanics_control::AnalogCompact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neuromechanics_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'neuromechanics_control': ['/home/baxter/git_repos/NeuromechanicsControl/ROS-packages/control/src/neuromechanics_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea5427e49e87b7ab7e158529f350df24";
  }

  static const char* value(const ::neuromechanics_control::AnalogCompact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea5427e49e87b7abULL;
  static const uint64_t static_value2 = 0x7e158529f350df24ULL;
};

template<class ContainerAllocator>
struct DataType< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neuromechanics_control/AnalogCompact";
  }

  static const char* value(const ::neuromechanics_control::AnalogCompact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] data\n\
string[]  names\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::neuromechanics_control::AnalogCompact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnalogCompact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neuromechanics_control::AnalogCompact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neuromechanics_control::AnalogCompact_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEUROMECHANICS_CONTROL_MESSAGE_ANALOGCOMPACT_H
