//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the neuromechanics_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __neuromechanics_control__EKEBERGCONFIG_H__
#define __neuromechanics_control__EKEBERGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace neuromechanics_control
{
  class EkebergConfigStatics;

  class EkebergConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(EkebergConfig &config, const EkebergConfig &max, const EkebergConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const EkebergConfig &config1, const EkebergConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, EkebergConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const EkebergConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, EkebergConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const EkebergConfig &config) const = 0;
      virtual void getValue(const EkebergConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T EkebergConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (EkebergConfig::* field);

      virtual void clamp(EkebergConfig &config, const EkebergConfig &max, const EkebergConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const EkebergConfig &config1, const EkebergConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, EkebergConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const EkebergConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, EkebergConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const EkebergConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const EkebergConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, EkebergConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, EkebergConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<EkebergConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(EkebergConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("s0_alpha"==(*_i)->name){s0_alpha = boost::any_cast<double>(val);}
        if("s0_beta"==(*_i)->name){s0_beta = boost::any_cast<double>(val);}
        if("s0_gamma"==(*_i)->name){s0_gamma = boost::any_cast<double>(val);}
        if("s0_delta"==(*_i)->name){s0_delta = boost::any_cast<double>(val);}
        if("s1_alpha"==(*_i)->name){s1_alpha = boost::any_cast<double>(val);}
        if("s1_beta"==(*_i)->name){s1_beta = boost::any_cast<double>(val);}
        if("s1_gamma"==(*_i)->name){s1_gamma = boost::any_cast<double>(val);}
        if("s1_delta"==(*_i)->name){s1_delta = boost::any_cast<double>(val);}
        if("e0_alpha"==(*_i)->name){e0_alpha = boost::any_cast<double>(val);}
        if("e0_beta"==(*_i)->name){e0_beta = boost::any_cast<double>(val);}
        if("e0_gamma"==(*_i)->name){e0_gamma = boost::any_cast<double>(val);}
        if("e0_delta"==(*_i)->name){e0_delta = boost::any_cast<double>(val);}
        if("e1_alpha"==(*_i)->name){e1_alpha = boost::any_cast<double>(val);}
        if("e1_beta"==(*_i)->name){e1_beta = boost::any_cast<double>(val);}
        if("e1_gamma"==(*_i)->name){e1_gamma = boost::any_cast<double>(val);}
        if("e1_delta"==(*_i)->name){e1_delta = boost::any_cast<double>(val);}
        if("w0_alpha"==(*_i)->name){w0_alpha = boost::any_cast<double>(val);}
        if("w0_beta"==(*_i)->name){w0_beta = boost::any_cast<double>(val);}
        if("w0_gamma"==(*_i)->name){w0_gamma = boost::any_cast<double>(val);}
        if("w0_delta"==(*_i)->name){w0_delta = boost::any_cast<double>(val);}
        if("w1_alpha"==(*_i)->name){w1_alpha = boost::any_cast<double>(val);}
        if("w1_beta"==(*_i)->name){w1_beta = boost::any_cast<double>(val);}
        if("w1_gamma"==(*_i)->name){w1_gamma = boost::any_cast<double>(val);}
        if("w1_delta"==(*_i)->name){w1_delta = boost::any_cast<double>(val);}
        if("w2_alpha"==(*_i)->name){w2_alpha = boost::any_cast<double>(val);}
        if("w2_beta"==(*_i)->name){w2_beta = boost::any_cast<double>(val);}
        if("w2_gamma"==(*_i)->name){w2_gamma = boost::any_cast<double>(val);}
        if("w2_delta"==(*_i)->name){w2_delta = boost::any_cast<double>(val);}
      }
    }

    double s0_alpha;
double s0_beta;
double s0_gamma;
double s0_delta;
double s1_alpha;
double s1_beta;
double s1_gamma;
double s1_delta;
double e0_alpha;
double e0_beta;
double e0_gamma;
double e0_delta;
double e1_alpha;
double e1_beta;
double e1_gamma;
double e1_delta;
double w0_alpha;
double w0_beta;
double w0_gamma;
double w0_delta;
double w1_alpha;
double w1_beta;
double w1_gamma;
double w1_delta;
double w2_alpha;
double w2_beta;
double w2_gamma;
double w2_delta;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_delta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_alpha;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_beta;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_gamma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_delta;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("EkebergConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const EkebergConfig &__max__ = __getMax__();
      const EkebergConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const EkebergConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const EkebergConfig &__getDefault__();
    static const EkebergConfig &__getMax__();
    static const EkebergConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const EkebergConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void EkebergConfig::ParamDescription<std::string>::clamp(EkebergConfig &config, const EkebergConfig &max, const EkebergConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class EkebergConfigStatics
  {
    friend class EkebergConfig;

    EkebergConfigStatics()
    {
EkebergConfig::GroupDescription<EkebergConfig::DEFAULT, EkebergConfig> Default("Default", "", 0, 0, true, &EkebergConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_alpha", "double", 0, "s0 - Muscle Gain (alpha)", "", &EkebergConfig::s0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_alpha", "double", 0, "s0 - Muscle Gain (alpha)", "", &EkebergConfig::s0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_beta", "double", 0, "s0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::s0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_beta", "double", 0, "s0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::s0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_gamma", "double", 0, "s0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_gamma", "double", 0, "s0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_delta", "double", 0, "s0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s0_delta", "double", 0, "s0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_alpha", "double", 0, "s1 - Muscle Gain (alpha)", "", &EkebergConfig::s1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_alpha", "double", 0, "s1 - Muscle Gain (alpha)", "", &EkebergConfig::s1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_beta", "double", 0, "s1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::s1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_beta", "double", 0, "s1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::s1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_gamma", "double", 0, "s1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_gamma", "double", 0, "s1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_delta", "double", 0, "s1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("s1_delta", "double", 0, "s1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::s1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_alpha", "double", 0, "e0 - Muscle Gain (alpha)", "", &EkebergConfig::e0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_alpha", "double", 0, "e0 - Muscle Gain (alpha)", "", &EkebergConfig::e0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_beta", "double", 0, "e0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::e0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_beta", "double", 0, "e0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::e0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_gamma", "double", 0, "e0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_gamma", "double", 0, "e0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_delta", "double", 0, "e0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e0_delta", "double", 0, "e0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_alpha", "double", 0, "e1 - Muscle Gain (alpha)", "", &EkebergConfig::e1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_alpha", "double", 0, "e1 - Muscle Gain (alpha)", "", &EkebergConfig::e1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_beta", "double", 0, "e1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::e1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_beta", "double", 0, "e1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::e1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_gamma", "double", 0, "e1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_gamma", "double", 0, "e1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_delta", "double", 0, "e1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("e1_delta", "double", 0, "e1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::e1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_alpha", "double", 0, "w0 - Muscle Gain (alpha)", "", &EkebergConfig::w0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_alpha", "double", 0, "w0 - Muscle Gain (alpha)", "", &EkebergConfig::w0_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_beta", "double", 0, "w0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_beta", "double", 0, "w0 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w0_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_gamma", "double", 0, "w0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_gamma", "double", 0, "w0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w0_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_delta", "double", 0, "w0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w0_delta", "double", 0, "w0 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w0_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_alpha", "double", 0, "w1 - Muscle Gain (alpha)", "", &EkebergConfig::w1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_alpha", "double", 0, "w1 - Muscle Gain (alpha)", "", &EkebergConfig::w1_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_beta", "double", 0, "w1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_beta", "double", 0, "w1 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w1_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_gamma", "double", 0, "w1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_gamma", "double", 0, "w1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w1_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_delta", "double", 0, "w1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w1_delta", "double", 0, "w1 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w1_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_alpha = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_alpha = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_alpha", "double", 0, "w2 - Muscle Gain (alpha)", "", &EkebergConfig::w2_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_alpha", "double", 0, "w2 - Muscle Gain (alpha)", "", &EkebergConfig::w2_alpha)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_beta = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_beta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_beta", "double", 0, "w2 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w2_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_beta", "double", 0, "w2 - Muscle Stiffness Gain (beta)", "", &EkebergConfig::w2_beta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_gamma = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_gamma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_gamma", "double", 0, "w2 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w2_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_gamma", "double", 0, "w2 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w2_gamma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_delta = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_delta = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_delta = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_delta", "double", 0, "w2 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w2_delta)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(EkebergConfig::AbstractParamDescriptionConstPtr(new EkebergConfig::ParamDescription<double>("w2_delta", "double", 0, "w2 - Muscle Tonic Stiffness (gamma)", "", &EkebergConfig::w2_delta)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(EkebergConfig::AbstractGroupDescriptionConstPtr(new EkebergConfig::GroupDescription<EkebergConfig::DEFAULT, EkebergConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<EkebergConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<EkebergConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<EkebergConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    EkebergConfig __max__;
    EkebergConfig __min__;
    EkebergConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const EkebergConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static EkebergConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &EkebergConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const EkebergConfig &EkebergConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const EkebergConfig &EkebergConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const EkebergConfig &EkebergConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<EkebergConfig::AbstractParamDescriptionConstPtr> &EkebergConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<EkebergConfig::AbstractGroupDescriptionConstPtr> &EkebergConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const EkebergConfigStatics *EkebergConfig::__get_statics__()
  {
    const static EkebergConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = EkebergConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __EKEBERGRECONFIGURATOR_H__
