//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the neuromechanics_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __neuromechanics_control__JOINTSPDCONFIG_H__
#define __neuromechanics_control__JOINTSPDCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace neuromechanics_control
{
  class JointsPDConfigStatics;

  class JointsPDConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(JointsPDConfig &config, const JointsPDConfig &max, const JointsPDConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const JointsPDConfig &config1, const JointsPDConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, JointsPDConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const JointsPDConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, JointsPDConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const JointsPDConfig &config) const = 0;
      virtual void getValue(const JointsPDConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T JointsPDConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (JointsPDConfig::* field);

      virtual void clamp(JointsPDConfig &config, const JointsPDConfig &max, const JointsPDConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const JointsPDConfig &config1, const JointsPDConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, JointsPDConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const JointsPDConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, JointsPDConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const JointsPDConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const JointsPDConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, JointsPDConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, JointsPDConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<JointsPDConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(JointsPDConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("s0_kp"==(*_i)->name){s0_kp = boost::any_cast<double>(val);}
        if("s0_kd"==(*_i)->name){s0_kd = boost::any_cast<double>(val);}
        if("s0_max_torque"==(*_i)->name){s0_max_torque = boost::any_cast<double>(val);}
        if("s1_kp"==(*_i)->name){s1_kp = boost::any_cast<double>(val);}
        if("s1_kd"==(*_i)->name){s1_kd = boost::any_cast<double>(val);}
        if("s1_max_torque"==(*_i)->name){s1_max_torque = boost::any_cast<double>(val);}
        if("e0_kp"==(*_i)->name){e0_kp = boost::any_cast<double>(val);}
        if("e0_kd"==(*_i)->name){e0_kd = boost::any_cast<double>(val);}
        if("e0_max_torque"==(*_i)->name){e0_max_torque = boost::any_cast<double>(val);}
        if("e1_kp"==(*_i)->name){e1_kp = boost::any_cast<double>(val);}
        if("e1_kd"==(*_i)->name){e1_kd = boost::any_cast<double>(val);}
        if("e1_max_torque"==(*_i)->name){e1_max_torque = boost::any_cast<double>(val);}
        if("w0_kp"==(*_i)->name){w0_kp = boost::any_cast<double>(val);}
        if("w0_kd"==(*_i)->name){w0_kd = boost::any_cast<double>(val);}
        if("w0_max_torque"==(*_i)->name){w0_max_torque = boost::any_cast<double>(val);}
        if("w1_kp"==(*_i)->name){w1_kp = boost::any_cast<double>(val);}
        if("w1_kd"==(*_i)->name){w1_kd = boost::any_cast<double>(val);}
        if("w1_max_torque"==(*_i)->name){w1_max_torque = boost::any_cast<double>(val);}
        if("w2_kp"==(*_i)->name){w2_kp = boost::any_cast<double>(val);}
        if("w2_kd"==(*_i)->name){w2_kd = boost::any_cast<double>(val);}
        if("w2_max_torque"==(*_i)->name){w2_max_torque = boost::any_cast<double>(val);}
      }
    }

    double s0_kp;
double s0_kd;
double s0_max_torque;
double s1_kp;
double s1_kd;
double s1_max_torque;
double e0_kp;
double e0_kd;
double e0_max_torque;
double e1_kp;
double e1_kd;
double e1_max_torque;
double w0_kp;
double w0_kd;
double w0_max_torque;
double w1_kp;
double w1_kd;
double w1_max_torque;
double w2_kp;
double w2_kd;
double w2_max_torque;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s0_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double s1_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e0_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double e1_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w0_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w1_max_torque;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double w2_max_torque;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("JointsPDConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const JointsPDConfig &__max__ = __getMax__();
      const JointsPDConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const JointsPDConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const JointsPDConfig &__getDefault__();
    static const JointsPDConfig &__getMax__();
    static const JointsPDConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const JointsPDConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void JointsPDConfig::ParamDescription<std::string>::clamp(JointsPDConfig &config, const JointsPDConfig &max, const JointsPDConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class JointsPDConfigStatics
  {
    friend class JointsPDConfig;

    JointsPDConfigStatics()
    {
JointsPDConfig::GroupDescription<JointsPDConfig::DEFAULT, JointsPDConfig> Default("Default", "", 0, 0, true, &JointsPDConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_kp = 45.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_kp", "double", 0, "s0 - Joint Kp", "", &JointsPDConfig::s0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_kp", "double", 0, "s0 - Joint Kp", "", &JointsPDConfig::s0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_kd = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_kd = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_kd", "double", 0, "s0 - Joint Kd", "", &JointsPDConfig::s0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_kd", "double", 0, "s0 - Joint Kd", "", &JointsPDConfig::s0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s0_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s0_max_torque = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s0_max_torque = 12.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_max_torque", "double", 0, "s0 - Max torque.", "", &JointsPDConfig::s0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s0_max_torque", "double", 0, "s0 - Max torque.", "", &JointsPDConfig::s0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_kp = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_kp", "double", 0, "s1 - Joint Kp", "", &JointsPDConfig::s1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_kp", "double", 0, "s1 - Joint Kp", "", &JointsPDConfig::s1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_kd = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_kd = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_kd", "double", 0, "s1 - Joint Kd", "", &JointsPDConfig::s1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_kd", "double", 0, "s1 - Joint Kd", "", &JointsPDConfig::s1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.s1_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.s1_max_torque = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.s1_max_torque = 19.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_max_torque", "double", 0, "s1 - Max torque.", "", &JointsPDConfig::s1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("s1_max_torque", "double", 0, "s1 - Max torque.", "", &JointsPDConfig::s1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_kp = 17.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_kp", "double", 0, "e0 - Joint Kp", "", &JointsPDConfig::e0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_kp", "double", 0, "e0 - Joint Kp", "", &JointsPDConfig::e0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_kd = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_kd = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_kd", "double", 0, "e0 - Joint Kd", "", &JointsPDConfig::e0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_kd", "double", 0, "e0 - Joint Kd", "", &JointsPDConfig::e0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e0_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e0_max_torque = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e0_max_torque = 3.75;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_max_torque", "double", 0, "e0 - Max torque.", "", &JointsPDConfig::e0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e0_max_torque", "double", 0, "e0 - Max torque.", "", &JointsPDConfig::e0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_kp = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_kp", "double", 0, "e1 - Joint Kp", "", &JointsPDConfig::e1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_kp", "double", 0, "e1 - Joint Kp", "", &JointsPDConfig::e1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_kd = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_kd = 4.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_kd", "double", 0, "e1 - Joint Kd", "", &JointsPDConfig::e1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_kd", "double", 0, "e1 - Joint Kd", "", &JointsPDConfig::e1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.e1_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.e1_max_torque = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.e1_max_torque = 10.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_max_torque", "double", 0, "e1 - Max torque.", "", &JointsPDConfig::e1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("e1_max_torque", "double", 0, "e1 - Max torque.", "", &JointsPDConfig::e1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_kp = 300.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_kp = 22.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_kp", "double", 0, "w0 - Joint Kp", "", &JointsPDConfig::w0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_kp", "double", 0, "w0 - Joint Kp", "", &JointsPDConfig::w0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_kd = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_kd = 2.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_kd", "double", 0, "w0 - Joint Kd", "", &JointsPDConfig::w0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_kd", "double", 0, "w0 - Joint Kd", "", &JointsPDConfig::w0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w0_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w0_max_torque = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w0_max_torque = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_max_torque", "double", 0, "w0 - Max torque.", "", &JointsPDConfig::w0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w0_max_torque", "double", 0, "w0 - Max torque.", "", &JointsPDConfig::w0_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_kp = 300.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_kp = 27.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_kp", "double", 0, "w1 - Joint Kp", "", &JointsPDConfig::w1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_kp", "double", 0, "w1 - Joint Kp", "", &JointsPDConfig::w1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_kd = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_kd = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_kd", "double", 0, "w1 - Joint Kd", "", &JointsPDConfig::w1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_kd", "double", 0, "w1 - Joint Kd", "", &JointsPDConfig::w1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w1_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w1_max_torque = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w1_max_torque = 3.75;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_max_torque", "double", 0, "w1 - Max torque.", "", &JointsPDConfig::w1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w1_max_torque", "double", 0, "w1 - Max torque.", "", &JointsPDConfig::w1_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_kp = 300.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_kp", "double", 0, "w2 - Joint Kp", "", &JointsPDConfig::w2_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_kp", "double", 0, "w2 - Joint Kp", "", &JointsPDConfig::w2_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_kd = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_kd", "double", 0, "w2 - Joint Kd", "", &JointsPDConfig::w2_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_kd", "double", 0, "w2 - Joint Kd", "", &JointsPDConfig::w2_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.w2_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.w2_max_torque = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.w2_max_torque = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_max_torque", "double", 0, "w2 - Max torque.", "", &JointsPDConfig::w2_max_torque)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(JointsPDConfig::AbstractParamDescriptionConstPtr(new JointsPDConfig::ParamDescription<double>("w2_max_torque", "double", 0, "w2 - Max torque.", "", &JointsPDConfig::w2_max_torque)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(JointsPDConfig::AbstractGroupDescriptionConstPtr(new JointsPDConfig::GroupDescription<JointsPDConfig::DEFAULT, JointsPDConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<JointsPDConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<JointsPDConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<JointsPDConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    JointsPDConfig __max__;
    JointsPDConfig __min__;
    JointsPDConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const JointsPDConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static JointsPDConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &JointsPDConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const JointsPDConfig &JointsPDConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const JointsPDConfig &JointsPDConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const JointsPDConfig &JointsPDConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<JointsPDConfig::AbstractParamDescriptionConstPtr> &JointsPDConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<JointsPDConfig::AbstractGroupDescriptionConstPtr> &JointsPDConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const JointsPDConfigStatics *JointsPDConfig::__get_statics__()
  {
    const static JointsPDConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = JointsPDConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __JOINTSPDRECONFIGURATOR_H__
