// Generated by gencpp from file neuromechanics_control/LearningState.msg
// DO NOT EDIT!


#ifndef NEUROMECHANICS_CONTROL_MESSAGE_LEARNINGSTATE_H
#define NEUROMECHANICS_CONTROL_MESSAGE_LEARNINGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neuromechanics_control
{
template <class ContainerAllocator>
struct LearningState_
{
  typedef LearningState_<ContainerAllocator> Type;

  LearningState_()
    : header()
    , learning(false)  {
    }
  LearningState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , learning(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _learning_type;
  _learning_type learning;





  typedef boost::shared_ptr< ::neuromechanics_control::LearningState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neuromechanics_control::LearningState_<ContainerAllocator> const> ConstPtr;

}; // struct LearningState_

typedef ::neuromechanics_control::LearningState_<std::allocator<void> > LearningState;

typedef boost::shared_ptr< ::neuromechanics_control::LearningState > LearningStatePtr;
typedef boost::shared_ptr< ::neuromechanics_control::LearningState const> LearningStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neuromechanics_control::LearningState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neuromechanics_control::LearningState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neuromechanics_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'neuromechanics_control': ['/home/baxter/git_repos/NeuromechanicsControl/ROS-packages/control/src/neuromechanics_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::LearningState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::LearningState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::LearningState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::LearningState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::LearningState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::LearningState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neuromechanics_control::LearningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef2f83334187d4def2eb42802f8414ef";
  }

  static const char* value(const ::neuromechanics_control::LearningState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef2f83334187d4deULL;
  static const uint64_t static_value2 = 0xf2eb42802f8414efULL;
};

template<class ContainerAllocator>
struct DataType< ::neuromechanics_control::LearningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neuromechanics_control/LearningState";
  }

  static const char* value(const ::neuromechanics_control::LearningState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neuromechanics_control::LearningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool learning\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::neuromechanics_control::LearningState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neuromechanics_control::LearningState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.learning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearningState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neuromechanics_control::LearningState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neuromechanics_control::LearningState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "learning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.learning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEUROMECHANICS_CONTROL_MESSAGE_LEARNINGSTATE_H
