// Generated by gencpp from file neuromechanics_control/Spike_group.msg
// DO NOT EDIT!


#ifndef NEUROMECHANICS_CONTROL_MESSAGE_SPIKE_GROUP_H
#define NEUROMECHANICS_CONTROL_MESSAGE_SPIKE_GROUP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neuromechanics_control
{
template <class ContainerAllocator>
struct Spike_group_
{
  typedef Spike_group_<ContainerAllocator> Type;

  Spike_group_()
    : neuron_index()
    , time()  {
    }
  Spike_group_(const ContainerAllocator& _alloc)
    : neuron_index(_alloc)
    , time(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _neuron_index_type;
  _neuron_index_type neuron_index;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::neuromechanics_control::Spike_group_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neuromechanics_control::Spike_group_<ContainerAllocator> const> ConstPtr;

}; // struct Spike_group_

typedef ::neuromechanics_control::Spike_group_<std::allocator<void> > Spike_group;

typedef boost::shared_ptr< ::neuromechanics_control::Spike_group > Spike_groupPtr;
typedef boost::shared_ptr< ::neuromechanics_control::Spike_group const> Spike_groupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neuromechanics_control::Spike_group_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neuromechanics_control::Spike_group_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neuromechanics_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'neuromechanics_control': ['/home/baxter/git_repos/NeuromechanicsControl/ROS-packages/control/src/neuromechanics_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neuromechanics_control::Spike_group_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuromechanics_control::Spike_group_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuromechanics_control::Spike_group_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981939a1e507ff75c61993d24854ca72";
  }

  static const char* value(const ::neuromechanics_control::Spike_group_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981939a1e507ff75ULL;
  static const uint64_t static_value2 = 0xc61993d24854ca72ULL;
};

template<class ContainerAllocator>
struct DataType< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neuromechanics_control/Spike_group";
  }

  static const char* value(const ::neuromechanics_control::Spike_group_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] neuron_index\n\
float64[] time\n\
";
  }

  static const char* value(const ::neuromechanics_control::Spike_group_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.neuron_index);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Spike_group_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neuromechanics_control::Spike_group_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neuromechanics_control::Spike_group_<ContainerAllocator>& v)
  {
    s << indent << "neuron_index[]" << std::endl;
    for (size_t i = 0; i < v.neuron_index.size(); ++i)
    {
      s << indent << "  neuron_index[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.neuron_index[i]);
    }
    s << indent << "time[]" << std::endl;
    for (size_t i = 0; i < v.time.size(); ++i)
    {
      s << indent << "  time[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.time[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEUROMECHANICS_CONTROL_MESSAGE_SPIKE_GROUP_H
